#!/usr/bin/env tsx
/**
 * Applies every SQL file under `migrations/` that hasn't run yet. Plain SQL,
 * generated by `pnpm --filter @lecturebrief/db generate` — see BUILD_PLAN.md
 * §2: "Drizzle because migrations are plain SQL you can read."
 */

import { fileURLToPath } from "node:url";
import { Pool } from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";

const url = process.env["DATABASE_URL"];
if (!url) throw new Error("DATABASE_URL is not set. See .env.example.");

const pool = new Pool({ connectionString: url });
const db = drizzle(pool);

const migrationsFolder = fileURLToPath(new URL("../migrations", import.meta.url));
await migrate(db, { migrationsFolder });
console.log("migrations applied");
await pool.end();
